# -*- coding: utf-8 -*-
"""Copy of KNN-mnist.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EaWSa6K3T2W8fPA_y5C-IG-XnzAQcjOS

اجرای کا-نزدیک‌ترین همسایگی بر روی مجموعه داده ارقام انگلیسی

کد اصلی برگرفته از گیت‌هاب زیر:

https://github.com/MarianaBazely

<a href="https://colab.research.google.com/github/mamintoosi/DM/blob/master/code/KNN/KNN-mnist.ipynb"><img align="left" src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab" title="Open and Execute in Google Colaboratory"></a>
"""

# K-Nearest Neighbor Classification
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, accuracy_score
from sklearn import datasets
import numpy as np
from matplotlib import pyplot as plt

# load the MNIST digits dataset
mnist = datasets.load_digits()

#print (mnist.data)

# Training and testing split,
# 75% for training and 25% for testing
(x_train, x_test, y_train, y_test) = train_test_split(np.array(mnist.data), mnist.target, test_size=0.25)#, random_state=42)

# Checking sizes of each data split
print("training data points: {}".format(len(y_train)))
print("testing data points: {}".format(len(y_test)))

mnist.data.shape

# visualize
plt.figure
for i in range(9):
    plt.subplot(3, 3, i+1)
    plt.imshow(x_train[i].reshape(8, 8), cmap='gray')
    plt.title(y_train[i])
    plt.axis('off')
    plt.savefig('mnist_plot.png')
plt.show()

knn_clf = KNeighborsClassifier()
knn_clf.fit(x_train, y_train)

preds = knn_clf.predict(x_test)
accuracy = accuracy_score(y_test, preds)
print(accuracy)

preds.shape

# initialize the values of k for our k-Nearest Neighbor classifier along with the
# list of accuracies for each value of k
kVals = range(3, 20, 2)
accuracies = []

# take 10% of the training data and use that for validation
(x_train, x_val, y_train, y_val) = train_test_split(x_train, y_train, test_size=0.1)#, random_state=84)

# loop over kVals
for k in kVals:
    # train the classifier with the current value of `k`
    model = KNeighborsClassifier(n_neighbors=k)
    model.fit(x_train, y_train)

    # evaluate the model and print the accuracies list
    score = model.score(x_val, y_val)
    print("k=%d, accuracy=%.2f%%" % (k, score * 100))
    accuracies.append(score)

# largest accuracy
# np.argmax returns the indices of the maximum values along an axis
i = np.argmax(accuracies)
print("k=%d achieved highest accuracy of %.2f%% on validation data" % (kVals[i],
    accuracies[i] * 100))

errs = [1-acc for acc in accuracies]
errs

# num_k = np.arange(1, 21)
plt.figure(dpi=100)
plt.style.use('ggplot')
plt.plot(kVals, errs)
plt.xlabel('Number of Neihgbors')
plt.ylabel('Test Error %')
# plt.savefig('err_plot.png')

# Now that I know the best value of k, re-train the classifier
model = KNeighborsClassifier(n_neighbors=kVals[i])
model.fit(x_train, y_train)

# Predict labels for the test set
predictions = model.predict(x_test)

# Evaluate performance of model for each of the digits
print("EVALUATION ON TESTING DATA")
print(classification_report(y_test, predictions))

# visualize
plt.figure
for i in range(9):
    plt.subplot(3, 3, i+1)
    plt.imshow(x_test[i].reshape(8, 8), cmap='gray')
    plt.title(predictions[i])
    plt.axis('off')
    plt.savefig('mnist_plot.png')
plt.show()