# -*- coding: utf-8 -*-
"""knn(iris).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gV5yKtgNn8I_N5vaQrwmO9fcQ_32KSFq
"""

# Import necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Load the Iris dataset
iris = load_iris()
X = iris.data  # Features
y = iris.target  # Target variable

# Create a DataFrame for better visualization
df = pd.DataFrame(X, columns=iris.feature_names)
df['species'] = y
df['species_name'] = [iris.target_names[i] for i in y]

print("First few rows of the dataset:")
print(df.head())
print("\nDataset info:")
print(df.info())

# Exploratory Data Analysis
print("\nStatistical summary:")
print(df.describe())

# Visualize the data
plt.figure(figsize=(15, 10))

# Pairplot to see relationships between features
plt.subplot(2, 2, 1)
sns.scatterplot(data=df, x='sepal length (cm)', y='sepal width (cm)', hue='species_name')
plt.title('Sepal Length vs Sepal Width')

plt.subplot(2, 2, 2)
sns.scatterplot(data=df, x='petal length (cm)', y='petal width (cm)', hue='species_name')
plt.title('Petal Length vs Petal Width')

plt.subplot(2, 2, 3)
sns.boxplot(data=df, x='species_name', y='sepal length (cm)')
plt.title('Sepal Length by Species')

plt.subplot(2, 2, 4)
sns.boxplot(data=df, x='species_name', y='petal length (cm)')
plt.title('Petal Length by Species')

plt.tight_layout()
plt.show()

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

# Feature scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Find the optimal K value
error_rates = []

for k in range(1, 40):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    pred_k = knn.predict(X_test)
    error_rates.append(np.mean(pred_k != y_test))

# Plot error rates
plt.figure(figsize=(10, 6))
plt.plot(range(1, 40), error_rates, color='blue', linestyle='dashed', marker='o',
         markerfacecolor='red', markersize=10)
plt.title('Error Rate vs K Value')
plt.xlabel('K')
plt.ylabel('Error Rate')
plt.show()

# Find the optimal K (with minimum error rate)
optimal_k = error_rates.index(min(error_rates)) + 1
print(f"Optimal K value: {optimal_k}")

# Train the KNN model with optimal K
knn = KNeighborsClassifier(n_neighbors=optimal_k)
knn.fit(X_train, y_train)

# Make predictions
y_pred = knn.predict(X_test)

# Evaluate the model
print("\nModel Evaluation:")
print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=iris.target_names))

# Function to predict new samples
def predict_iris_sample(sepal_length, sepal_width, petal_length, petal_width):
    """
    Predict the species of a new iris flower sample
    """
    sample = np.array([[sepal_length, sepal_width, petal_length, petal_width]])
    sample_scaled = scaler.transform(sample)
    prediction = knn.predict(sample_scaled)
    probability = knn.predict_proba(sample_scaled)

    species_name = iris.target_names[prediction[0]]
    confidence = np.max(probability) * 100

    print(f"Predicted species: {species_name}")
    print(f"Confidence: {confidence:.2f}%")
    print("Probabilities for each class:")
    for i, species in enumerate(iris.target_names):
        print(f"  {species}: {probability[0][i]:.4f}")

    return species_name

# Test with a sample prediction
print("\nSample Prediction:")
predict_iris_sample(5.1, 3.5, 1.4, 0.2)

# Compare different K values
k_values = [1, 3, 5, 7, optimal_k, 15]
accuracies = []

for k in k_values:
    knn_temp = KNeighborsClassifier(n_neighbors=k)
    knn_temp.fit(X_train, y_train)
    y_pred_temp = knn_temp.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred_temp)
    accuracies.append(accuracy)
    print(f"K = {k}: Accuracy = {accuracy:.4f}")

# Plot accuracies for different K values
plt.figure(figsize=(10, 6))
plt.plot(k_values, accuracies, marker='o')
plt.title('Accuracy vs K Value')
plt.xlabel('K Value')
plt.ylabel('Accuracy')
plt.grid(True)
plt.show()