# -*- coding: utf-8 -*-
"""Percptron 1 laye.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1spofqoQ6h9GU8oc3fTycp0v6UaU_PSe4
"""

pip install numpy

import numpy as np

# 1. داده‌های آموزشی (مثال‌های واقعی)
# هر ردیف: [قیمت (میلیون تومان), مساحت (متر مربع)]
# برچسب‌ها: 0 = ارزان، 1 = گران
X_train = np.array([
    [80, 50],   # خانه ارزان
    [120, 60],  # خانه گران
    [60, 40],   # خانه ارزان
    [150, 80],  # خانه گران
    [90, 55],   # خانه ارزان
    [180, 90],  # خانه گران
    [70, 45],   # خانه ارزان
    [200, 100]  # خانه گران
])

y_train = np.array([0, 1, 0, 1, 0, 1, 0, 1])  # برچسب‌ها

# 2. کلاس پرسپترون تک‌لایه
class HousePricePerceptron:
    def __init__(self):
        # وزن‌های اولیه تصادفی
        self.w_price = np.random.randn() * 0.01  # وزن قیمت
        self.w_area = np.random.randn() * 0.01   # وزن مساحت
        self.bias = np.random.randn() * 0.01     # بایاس
        self.lr = 0.01  # نرخ یادگیری

    def predict(self, price, area):
        """پیش‌بینی برای یک خانه"""
        # جمع‌وزنی
        z = (self.w_price * price) + (self.w_area * area) + self.bias

        # تابع پلهای
        if z >= 0:
            return 1  # گران
        else:
            return 0  # ارزان

    def train(self, X, y, epochs=100):
        """آموزش مدل"""
        print("شروع آموزش...")
        print(f"وزن اولیه: w_price={self.w_price:.3f}, w_area={self.w_area:.3f}, bias={self.bias:.3f}")
        print("-" * 50)

        for epoch in range(epochs):
            total_error = 0

            for i in range(len(X)):
                # داده فعلی
                price = X[i][0]
                area = X[i][1]
                true_label = y[i]

                # پیش‌بینی
                prediction = self.predict(price, area)

                # خطا
                error = true_label - prediction
                total_error += abs(error)

                # به‌روزرسانی وزن‌ها (قاعده پرسپترون)
                self.w_price += self.lr * error * price
                self.w_area += self.lr * error * area
                self.bias += self.lr * error

            # نمایش پیشرفت هر 20 دوره
            if (epoch + 1) % 20 == 0:
                print(f"دوره {epoch+1:3d} | خطای کل: {total_error:5.2f} | "
                      f"وزن‌ها: price={self.w_price:7.3f}, area={self.w_area:7.3f}, bias={self.bias:7.3f}")

    def explain(self):
        """توضیح مدل یادگرفته‌شده"""
        print("\n" + "="*60)
        print("تحلیل مدل آموزش‌دیده:")
        print("="*60)

        print(f"\nوزن قیمت (w_price) = {self.w_price:.3f}")
        print("↳ هر 1 میلیون افزایش قیمت، امتیاز خانه را {:.3f} واحد {} می‌کند".format(
            abs(self.w_price), "افزایش" if self.w_price > 0 else "کاهش"
        ))

        print(f"\nوزن مساحت (w_area) = {self.w_area:.3f}")
        print("↳ هر 1 متر افزایش مساحت، امتیاز خانه را {:.3f} واحد {} می‌کند".format(
            abs(self.w_area), "افزایش" if self.w_area > 0 else "کاهش"
        ))

        print(f"\nبایاس = {self.bias:.3f}")
        print("↳ تمایل ذاتی مدل به سمت '{}' است".format(
            "گران (خروجی 1)" if self.bias > 0 else "ارزان (خروجی 0)"
        ))

        print("\nمعادله تصمیم‌گیری:")
        print(f"امتیاز = ({self.w_price:.3f} × قیمت) + ({self.w_area:.3f} × مساحت) + ({self.bias:.3f})")
        print("اگر امتیاز ≥ 0 → گران (1)، در غیر این صورت → ارزان (0)")

# 3. آموزش مدل
print("🚀 پرسپترون تشخیص قیمت خانه")
print("="*60)

# ایجاد و آموزش مدل
perceptron = HousePricePerceptron()
perceptron.train(X_train, y_train, epochs=100)

# 4. نمایش تحلیل مدل
perceptron.explain()

# 5. تست با داده‌های جدید
print("\n" + "="*60)
print("تست با خانه‌های جدید:")
print("="*60)

test_houses = [
    [95, 60],   # باید ارزان باشد
    [160, 85],  # باید گران باشد
    [50, 30],   # قطعاً ارزان
    [220, 110]  # قطعاً گران
]

for i, (price, area) in enumerate(test_houses):
    prediction = perceptron.predict(price, area)

    # محاسبه امتیاز دقیق
    score = (perceptron.w_price * price) + (perceptron.w_area * area) + perceptron.bias

    print(f"\nخانه {i+1}: قیمت={price} میلیون، مساحت={area} متر")
    print(f"  امتیاز: {score:.2f}")
    print(f"  پیش‌بینی: {'💰 گران' if prediction == 1 else '💸 ارزان'}")

    # توضیح تصمیم
    if prediction == 1:
        print(f"  دلیل: امتیاز ({score:.2f}) ≥ 0")
    else:
        print(f"  دلیل: امتیاز ({score:.2f}) < 0")

# 6. رسم مرز تصمیم‌گیری
print("\n" + "="*60)
print("🎯 مرز تصمیم‌گیری مدل:")
print("="*60)

# محاسبه معادله خط مرز (حل: w1*x1 + w2*x2 + b = 0)
# x2 = (-w1*x1 - b) / w2
w1, w2, b = perceptron.w_price, perceptron.w_area, perceptron.bias

if w2 != 0:
    # دو نقطه برای رسم خط
    x_line = np.array([40, 250])  # محدوده قیمت
    y_line = (-w1 * x_line - b) / w2

    print(f"\nمعادله مرز تصمیم:")
    print(f"مساحت = ({-w1/w2:.3f} × قیمت) + ({-b/w2:.3f})")

    print("\n📊 تفسیر:")
    print("خانه‌هایی که در بالای این خط هستند → گران")
    print("خانه‌هایی که در پایین این خط هستند → ارزان")
else:
    print("خط عمودی (فقط بر اساس قیمت تصمیم می‌گیرد)")